pluginList = ['Sofa.Component.Collision.Geometry',
              'Sofa.Component.IO.Mesh',
              'Sofa.Component.LinearSolver.Iterative',
              'Sofa.Component.Mapping.NonLinear',
              'Sofa.Component.ODESolver.Backward',
              'Sofa.Component.StateContainer',
              'Sofa.Component.Topology.Container.Constant',
              'Sofa.Component.Visual',
              'Sofa.GL.Component.Rendering3D',
              'Sofa.Component.Constraint.Projective',
              'Sofa.Component.LinearSolver.Direct',
              'Sofa.Component.Topology.Container.Dynamic',
              'Sofa.Component.Topology.Mapping',
              'Sofa.Component.Mapping.Linear',
              'Sofa.Component.Topology.Container.Grid',
              'Sofa.Component.SolidMechanics.Spring',
              'Sofa.Component.Collision.Detection.Intersection',
              'Sofa.Component.Collision.Response.Contact',
              'Sofa.Component.Constraint.Lagrangian.Solver',
              'Sofa.Component.AnimationLoop',
              'Sofa.Component.Collision.Detection.Algorithm',
              'Sofa.Component.Constraint.Lagrangian.Correction',
              'BeamAdapter']
display = ["showBehaviorModels","showCollisionModels","hideBoundingCollisionModels","showForceFields","showVisualModels","showInteractionForceFields"]
# display = ["showBehaviorModels","showCollisionModels","hideBoundingCollisionModels","showForceFields"]