import numpy as np
def Centra_actuation_function(current_vec):
    """
    This function computes the corresponding magnetic field for a given input current configuration

    Input: 
    current_vec: a 1D array vec containing 6 input current amplitudes. Each elem range in (-1,1)

    Output:
    magnetic_field: 1D array magnetic field generated by electromagnet

    """

   
    Centra_actuation_matrix = 1e3* np.array([
        [
            9.4656140092186, 4.74505490837684 , -4.71391866613356 , -9.51434537888391 , -4.733286924  , 4.736708952  , 9.462962932  , 4.772773998  , -4.775126736  , -9.581367831  , -4.720185503  , 4.758980296
        ],
        [
            0.005756584 , 8.196355606 , 8.27455056019098 , -0.0020139742946912 , -8.24877461710683 , -8.20554829909761  , 0.0153504597626003 , 8.18024888860468 , 8.34339188820941, -0.016143715344311 , -8.29034850156213 , -8.21870703754907
        ],
        [
            7.28803575942369  , 7.28971863310728  , 7.33748694910782  , 7.30496227337128  , 7.32028910323302  , 7.27946222262144  , -7.27534314912205  , -7.24283963971174  , -7.30446165706031  , -7.34493703378806  , -7.25576700275291  , -7.26664687530789
        ]
    ]) # mT/A

    # rotation_matrix = np.array([
    #     [np.cos(np.pi/3), -np.sin(np.pi/3), 0],
    #     [np.sin(np.pi/3), np.cos(np.pi/3),  0],
    #     [0              , 0              ,  1]
    # ])

    magnetic_field = Centra_actuation_matrix[...,:6]@ current_vec

    return magnetic_field